[features]
seeds = false
skip-lint = false
[programs.localnet]
notes = "8ckqj6yfYw9ZpFjM4VcUQ76u6ocZTk78Z9YNAgRUwKkd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/anamansari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
